export const mockModerationHistory = [
  {
    id: 1,
    moderatorId: 101,
    moderatorName: "Иван Петров",
    action: "approved",
    reason: null,
    comment: "Все корректно, нарушений нет.",
    timestamp: "2025-01-15T10:24:00Z",
  },
  {
    id: 2,
    moderatorId: 102,
    moderatorName: "Анна Смирнова",
    action: "requestChanges",
    reason: "Некорректное описание",
    comment: "Уточните параметры товара и добавьте больше фото.",
    timestamp: "2025-01-16T14:42:00Z",
  },
  {
    id: 3,
    moderatorId: 103,
    moderatorName: "Дмитрий Орлов",
    action: "rejected",
    reason: "Запрещенный товар",
    comment: "Объявление нарушает правила платформы.",
    timestamp: "2025-01-17T08:10:00Z",
  },
  {
    id: 4,
    moderatorId: 104,
    moderatorName: "Елена Кузнецова",
    action: "approved",
    reason: null,
    comment: "Исправления учтены, можно публиковать.",
    timestamp: "2025-01-18T11:59:00Z",
  },
  {
    id: 5,
    moderatorId: 105,
    moderatorName: "Максим Руденко",
    action: "requestChanges",
    reason: "Проблемы с фото",
    comment: "Некоторые изображения не загружаются.",
    timestamp: "2025-01-19T09:33:00Z",
  },
  {
    id: 6,
    moderatorId: 106,
    moderatorName: "Ольга Власова",
    action: "approved",
    reason: null,
    comment: "",
    timestamp: "2025-01-20T16:47:00Z",
  },
  {
    id: 7,
    moderatorId: 107,
    moderatorName: "Сергей Волков",
    action: "rejected",
    reason: "Подозрение на мошенничество",
    comment: "Несовпадение данных продавца.",
    timestamp: "2025-01-21T12:20:00Z",
  },
  {
    id: 8,
    moderatorId: 108,
    moderatorName: "Мария Жукова",
    action: "requestChanges",
    reason: "Неверная категория",
    comment: "Перенесите объявление в корректный раздел.",
    timestamp: "2025-01-22T18:05:00Z",
  },
  {
    id: 9,
    moderatorId: 109,
    moderatorName: "Николай Захаров",
    action: "approved",
    reason: null,
    comment: "Категория исправлена, все ок.",
    timestamp: "2025-01-23T07:58:00Z",
  },
  {
    id: 10,
    moderatorId: 110,
    moderatorName: "Вера Литвинова",
    action: "rejected",
    reason: "Другое",
    comment: "Описание и фото слишком размытые, товар не понятен.",
    timestamp: "2025-01-24T15:12:00Z",
  },
];
